# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import detection_types_pb2 as detection__types__pb2


class AnomalyDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TwitterAnomalies = channel.unary_stream(
                '/AnomalyDetection/TwitterAnomalies',
                request_serializer=detection__types__pb2.Request.SerializeToString,
                response_deserializer=detection__types__pb2.Response.FromString,
                )


class AnomalyDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TwitterAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnomalyDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TwitterAnomalies': grpc.unary_stream_rpc_method_handler(
                    servicer.TwitterAnomalies,
                    request_deserializer=detection__types__pb2.Request.FromString,
                    response_serializer=detection__types__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AnomalyDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnomalyDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TwitterAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/AnomalyDetection/TwitterAnomalies',
            detection__types__pb2.Request.SerializeToString,
            detection__types__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
