# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anomaly_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import detection_types_pb2 as detection__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='anomaly_detection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61nomaly_detection.proto\x1a\x15\x64\x65tection_types.proto2a\n\x10\x41nomalyDetection\x12M\n\x10TwitterAnomalies\x12\x19.anomalydetection.Request\x1a\x1a.anomalydetection.Response\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[detection__types__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ANOMALYDETECTION = _descriptor.ServiceDescriptor(
  name='AnomalyDetection',
  full_name='AnomalyDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=50,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='TwitterAnomalies',
    full_name='AnomalyDetection.TwitterAnomalies',
    index=0,
    containing_service=None,
    input_type=detection__types__pb2._REQUEST,
    output_type=detection__types__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANOMALYDETECTION)

DESCRIPTOR.services_by_name['AnomalyDetection'] = _ANOMALYDETECTION

# @@protoc_insertion_point(module_scope)
